name: Deploy or Destroy AWS Infrastructure using CDK

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the action to perform: deploy or destroy"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      run: |
        python -m venv .venv  # Crear entorno virtual
        source .venv/bin/activate  # Activar entorno virtual
        pip install --upgrade pip  # Asegurarse de tener la última versión de pip
        pip install -r requirements.txt  # Instalar dependencias

    - name: Install AWS CDK
      run: |
        npm install -g aws-cdk  # Instalar CDK globalmente

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Execute CDK Action
      run: |
        source .venv/bin/activate  # Activar entorno virtual
        if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
          echo "Deploying infrastructure..."
          cdk deploy --require-approval never  # Desplegar la infraestructura
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          echo "Destroying infrastructure..."
          cdk destroy --force  # Destruir la infraestructura sin confirmación
        else
          echo "Invalid action: ${{ github.event.inputs.action }}"
          exit 1
        fi