name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      run: |
        python -m venv .venv  # Crear entorno virtual
        source .venv/bin/activate  # Activar entorno virtual
        pip install --upgrade pip  # Asegurarse de tener la última versión de pip
        pip install -r requirements.txt  # Instalar dependencias

    - name: Verify pytest installation
      run: |
        source .venv/bin/activate  # Activar entorno virtual
        pip show pytest  # Verificar que pytest esté instalado

    - name: Run tests
      run: |
        source .venv/bin/activate  # Activar entorno virtual
        pytest  # Ejecutar las pruebas